service: bolt-serverless-node-example

plugins:
  - serverless-offline
  - serverless-plugin-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  app:
    handler: handler.app
    events:
      - http:
          method: POST
          path: /slack/events
